# DIIE app
# by Josacc

library(patchwork)
library(scales)
library(plotly)
library(tidyverse)
library(readxl)
library(shiny)
library(shinymanager)
library(DT)


# Settings for shinyapss.io and Shiny Server
options(
  encoding               = "UTF-8",
  rsconnect.locale.cache = FALSE,
  rsconnect.locale       = "es_MX.utf8"
)
Sys.setlocale(locale = "es_MX.utf8")


# USER BASES ---------------------------------------------------------------

source("data/application_user_base.R")

set_labels(
  language              = "es",
  "Please authenticate" = "",
  "Username:"           = "Usuario:",
  "Password:"           = "Contraseña:",
  "Login"               = "Ingresar"
)

source("data/DIIE_user_base.R")


# IMPORT AND TIDY ----------------------------------------------------

# Databases current year
source("data/data_current_year.R")
source("functions/data_and_update.R")


# Local analysis.
# suppressMessages(suppressWarnings({
#   database_2023 <- data_and_update("xIktan_20231005104808909_reporteSegumiento.xlsx")[[1]]
#   .update_2023  <- data_and_update("xIktan_20231005104808909_reporteSegumiento.xlsx")[[2]]
# })
# )

# Local analysis.
# Vector de folios que no aplican a la fecha de corte.
# vec_folios_no_aplica <- DT_folio_no_aplica(database_2023) %>%
#   pull()


# EDA about "Observaciones" --------------------------------------------------

team_data <- function(team, data) {
  return(team %>% left_join(data, by = "Usuario", multiple = "all"))
}

# Principal observations database generated by reviewers 2023.
# Local analysis
# database_obs_2023 <- team_data(reviewer_team, database_2023) %>%
#   filter(`Cantidad de obs` > 0)

# Plot function top ten questions by project and module
source("functions/top_ten_questions.R")

# Entities vs observations
source("functions/entities_vs_observations.R")


# Data about previous year -------------------------------------------------

# Data base previous year
database_previous_year <- data_and_update("historial_seguimiento/xIktan_20231005104808909_reporteSegumiento.xlsx")[[1]]

# Folios "No aplica" previous year
vec_folios_no_aplica_previous_year <- DT_folio_no_aplica(database_previous_year) %>%
  pull()

# database_2023 <-
database_questionnaires_previous_year <- database_previous_year %>%
  filter(str_detect(Estatus, "Revisión OC"), Perfil == "RESPONSABLE OPERATIVO") %>%
  left_join(working_dates_previous_year, by = "Registro") %>% # Se modificó "Registro" para considerar solo días hábiles.
  select(-Registro) %>%
  rename(Registro = aux_var) %>%
  filter(!(Folio %in% vec_folios_no_aplica_previous_year))

# Plot about arrival general of questionnaires in previous year
plot_arrival_questionnaires_previous_year <- function(data, .week, .title = "") { #ajustar similar a la función sobre firma y sello

  suppressWarnings({
    .plot <- data %>%
      count(Registro) %>%
      rename(`Cuestionarios enviados a revisión OC` = names(.)[2]) %>%
      ggplot(aes(Registro, `Cuestionarios enviados a revisión OC`)) +
      geom_rect(aes(xmin = .week, xmax = .week + weeks(1),
                    ymin = 0, ymax = 50),
                fill = "grey", alpha = 3/4) +
      annotate("segment", x = DIIE_dates_previous_year[[2, 5]], xend = DIIE_dates_previous_year[[2, 5]], y = 0, yend = 50, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates_previous_year[[3, 5]], xend = DIIE_dates_previous_year[[3, 5]], y = 0, yend = 50, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates_previous_year[[4, 5]], xend = DIIE_dates_previous_year[[4, 5]], y = 0, yend = 50, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates_previous_year[[5, 5]], xend = DIIE_dates_previous_year[[5, 5]], y = 0, yend = 50, colour = "red", alpha = 1/2) +
      annotate("text", x = DIIE_dates_previous_year[[2, 5]], y = 52, label = str_c("Cierre cap. \n", DIIE_dates_previous_year[[2, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates_previous_year[[3, 5]], y = 52, label = str_c("Cierre cap. \n", DIIE_dates_previous_year[[3, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates_previous_year[[4, 5]], y = 52, label = str_c("Cierre cap. \n", DIIE_dates_previous_year[[4, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates_previous_year[[5, 5]], y = 52, label = str_c("Cierre cap. \n", DIIE_dates_previous_year[[5, 1]]), size = 2, color = "red") +
      geom_point(aes(color = -`Cuestionarios enviados a revisión OC`,
                     label1 = Registro, label2 = `Cuestionarios enviados a revisión OC`),
                 show.legend = FALSE) +
      scale_x_date(date_breaks = "week", date_labels = "%d %b") +
      ggtitle(.title) +
      theme_classic() +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 9),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10)
      )
  })

  return(ggplotly(.plot, tooltip = c("label1", "label2")))
}


# EDA about questionnaires "Revisión OC" -------------------------------------------------

# Database about questionnaires.
# Se modifica "Registro" para considerar solo días hábiles!
# Se descartan los folios que no aplican!
# Local analysis.
# database_questionnaires_2023 <- database_2023 %>%
#   filter(str_detect(Estatus, "Revisión OC"), Perfil == "RESPONSABLE OPERATIVO") %>%
#   left_join(working_dates, by = "Registro") %>% # Se modificó "Registro" para considerar solo días hábiles.
#   select(-Registro) %>%
#   rename(Registro = aux_var) %>%
#   filter(!(Folio %in% vec_folios_no_aplica))


count_arrival_questionnaires_week <- function(data, .week) {
  .n <- data %>%
    count(floor_date(Registro, "week", week_start = 1)) %>%
    rename(week = names(.)[1]) %>%
    filter(week == .week)

  if (nrow(.n) == 0) {
    return(0)
  }

  return(.n %>% .[[2]])
}

# Plot about arrival general of questionnaires in current year
plot_arrival_questionnaires_current_year <- function(data, .week, .title = "") { #ajustar similar a la función sobre firma y sello

  suppressWarnings({
    .plot <- data %>%
      count(Registro) %>%
      rename(`Cuestionarios enviados a revisión OC` = names(.)[2]) %>%
      ggplot(aes(Registro, `Cuestionarios enviados a revisión OC`)) +
      geom_rect(aes(xmin = .week, xmax = .week + weeks(1),
                    ymin = 0, ymax = 50),
                fill = "grey", alpha = 3/4) +
      annotate("segment", x = DIIE_dates[[2, 5]], xend = DIIE_dates[[2, 5]], y = 0, yend = 50, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[3, 5]], xend = DIIE_dates[[3, 5]], y = 0, yend = 50, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[4, 5]], xend = DIIE_dates[[4, 5]], y = 0, yend = 50, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[5, 5]], xend = DIIE_dates[[5, 5]], y = 0, yend = 50, colour = "red", alpha = 1/2) +
      annotate("text", x = DIIE_dates[[2, 5]], y = 52, label = str_c("Cierre cap. \n", DIIE_dates[[2, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates[[3, 5]], y = 52, label = str_c("Cierre cap. \n", DIIE_dates[[3, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates[[4, 5]], y = 52, label = str_c("Cierre cap. \n", DIIE_dates[[4, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates[[5, 5]], y = 52, label = str_c("Cierre cap. \n", DIIE_dates[[5, 1]]), size = 2, color = "red") +
      geom_point(aes(color = -`Cuestionarios enviados a revisión OC`,
                     label1 = Registro, label2 = `Cuestionarios enviados a revisión OC`),
                 show.legend = FALSE) +
      scale_x_date(date_breaks = "week", date_labels = "%d %b") +
      ggtitle(.title) +
      theme_classic() +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 9),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10)
      )
  })

  return(ggplotly(.plot, tooltip = c("label1", "label2")))
}

# Local analysis
# plot_arrival_questionnaires_current_year(database_questionnaires_2023, ymd("2023-03-28") + weeks(1), "2023")


# plot about arrival of questionnaires grid census
# Local analysis
# max_questionnaries_day_2023 <- database_questionnaires_2023 %>%
#   count(Registro, Censo) %>%
#   rename(`Cuestionarios enviados a revisión OC` = names(.)[[3]]) %>%
#   group_by(Censo) %>%
#   summarise(y_max = max(`Cuestionarios enviados a revisión OC`))

plot_arrival_questionnaires_grid_census_2023 <- function(data, max_day, .title = "") {

  .data <- data %>%
    count(Registro, Censo) %>%
    rename(`Cuestionarios enviados a revisión OC` = names(.)[[3]]) %>%
    left_join(DIIE_dates, by = c("Censo" = "name")) %>%
    left_join(max_day, by = "Censo")

  suppressWarnings({
    .plot <- .data %>%
      ggplot(aes(Registro, `Cuestionarios enviados a revisión OC`)) +
      geom_rect(aes(xmin = `start CE`, xmax = `end CE`,
                    ymin = 0, ymax = y_max + 1, Responsable = "CE"),
                fill = "green", alpha = 0.1) +
      geom_rect(aes(xmin = prosecution, xmax = diffusion,
                    ymin = 0, ymax = y_max + 1, Responsable = "SPICNG y SAICNG"),
                fill = "red", alpha = 0.3) +
      geom_rect(aes(xmin = `start DIIE`, xmax = `end DIIE`,
                    ymin = 0, ymax = y_max + 1, Responsable = "SOCNG"),
                fill = "orange", alpha = 0.5) +
      geom_point(size = 0.2, color = "blue") +
      facet_grid(Censo ~ ., scales = "free_y") +
      scale_x_date(date_breaks = "week", date_labels = "%d %b") +
      ggtitle(.title) +
      theme(
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1, size = 7),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 7),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10)
      )
  })

  return(ggplotly(.plot))
}

# Local analysis
# plot_arrival_questionnaires_grid_census_2023(database_questionnaires_2023, max_questionnaries_day_2023)

# Plot on arrival of questionnaires for entities grid census
max_questionnaries_day_entities_2023 <- function(data, entitie) {

  .data <- data %>%
    count(Registro, Entidad, Censo) %>%
    filter(Entidad == entitie) %>%
    rename(`Cuestionarios enviados a revisión OC` = names(.)[[4]]) %>%
    group_by(Censo) %>%
    summarise(y_max = max(`Cuestionarios enviados a revisión OC`))

  return(.data)
}

plot_arrival_questionnaires_entities_2023 <- function(data, entitie) {

  .data <- data %>%
    filter(Entidad == entitie)

  if (nrow(.data) == 0) {
    return(NULL)
  }

  suppressWarnings({
    .plot <- .data %>%
      count(Registro, Censo) %>%
      rename(`Cuestionarios enviados a revisión OC` = names(.)[[3]]) %>%
      left_join(DIIE_dates, by = c("Censo" = "name")) %>%
      left_join(max_questionnaries_day_entities_2023(data, entitie), by = "Censo") %>%
      ggplot(aes(Registro, `Cuestionarios enviados a revisión OC`)) +
      geom_rect(aes(xmin = `start CE`, xmax = `end CE`,
                    ymin = 0, ymax = y_max + 1, Responsable = "CE"),
                fill = "green", alpha = 0.1) +
      geom_rect(aes(xmin = prosecution, xmax = diffusion,
                    ymin = 0, ymax = y_max + 1, Responsable = "SPICNG y SAICNG"),
                fill = "red", alpha = 0.3) +
      geom_rect(aes(xmin = `start DIIE`, xmax = `end DIIE`,
                    ymin = 0, ymax = y_max + 1, Responsable = "SOCNG"),
                fill = "orange", alpha = 0.5) +
      geom_point(size = 1, color = "blue", alpha = 3/4) +
      facet_grid(Censo ~ ., scales = "free_y") +
      scale_x_date(date_breaks = "week", date_labels = "%d %b") +
      theme(
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1, size = 7),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 7),
        axis.title.y = element_blank()
        )
  })

  return(ggplotly(.plot))
}

# Local analysis
# plot_arrival_questionnaires_entities_2023(database_questionnaires_2023, levels(entities[[1]])[9])


# EDA about questionnaires "Firma y sello" ----------------------------------

# Database on questionnaires estatus firma y sello (1).
# Se modifica "Registro" para considerar solo días hábiles!
# Se descartan los folios que no aplican!
# Local analysis.
# database_questionnaires_firma_sello <- database_2023 %>%
#   filter(str_detect(Estatus, "En proceso de firma y sello \\(1\\)")) %>%
#   left_join(working_dates, by = "Registro") %>% # Se modificó "Registro" para considerar solo días hábiles.
#   select(-Registro) %>%
#   rename(Registro = aux_var) %>%
#   filter(!(Folio %in% vec_folios_no_aplica))


count_questionnaires_firma_sello_week <- function(data, .week) {
  .n <- data %>%
    count(floor_date(Registro, "week", week_start = 1)) %>%
    rename(week = names(.)[1]) %>%
    filter(week == .week)

  if (nrow(.n) == 0) {
    return(0)
  }

  return(.n %>% .[[2]])
}

# Local analysis
# count_questionnaires_firma_sello_week(database_questionnaires_firma_sello, ymd("2023-05-22"))

# DT on questionnaires set free by Registro
DT_questionnaires_firma_sello_registro <- function(.data) {

  .data %>%
    group_by(Registro) %>%
    dplyr::summarise(n = n(), `Folios<br>Cuestionarios en proceso de firma y sello (1)`= str_c(Folio, collapse = ", ")) %>%
    dplyr::arrange(desc(Registro))
}


# Plot on arrival general of questionnaires
plot_questionnaires_firma_sello <- function(data, .title = "") {

  ymax <- data %>%
    count(Registro) %>%
    arrange(desc(n)) %>%
    .[[1, 2]] + 5

  suppressWarnings({
    .plot <- data %>%
      group_by(Registro) %>%
      dplyr::summarise(n = n(), Folios = str_c(Folio, collapse = ", ")) %>%
      rename(`Cuestionarios en proceso de firma y sello (1)` = names(.)[2]) %>%
      ggplot(aes(Registro, `Cuestionarios en proceso de firma y sello (1)`)) +
      geom_point(aes(color = -`Cuestionarios en proceso de firma y sello (1)`,
                     label1 = Registro, label2 = `Cuestionarios en proceso de firma y sello (1)`),
                 show.legend = FALSE) +
      scale_x_date(date_breaks = "week", date_labels = "%d %b") +
      ggtitle(.title) +
      theme_classic() +
      theme(
        axis.text.x  = element_text(angle = 45, hjust = 1, size = 9),
        axis.title.x = element_blank(),
        axis.text.y  = element_text(size = 9),
        axis.title.y = element_blank(),
        plot.title   = element_text(size = 10)
      )
  })

  return(ggplotly(.plot, tooltip = c("label1", "label2")))
}

# Local analysis
# plot_questionnaires_firma_sello(database_questionnaires_firma_sello)

# Plot on questionnaires set free for week
plot_questionnaires_firma_sello_week <- function(data, .title = "") {

  .data <- data %>%
    count(ceiling_date(Registro, "week", week_start = 1)) %>%
    rename(Domingo = names(.)[1], `Cuestionarios acumulados en proceso de firma y sello (1)` = names(.)[2]) %>%
    transmute(Domingo = Domingo - 1, `Cuestionarios acumulados en proceso de firma y sello (1)`)

  ymax <- .data %>%
    arrange(desc(`Cuestionarios acumulados en proceso de firma y sello (1)`)) %>%
    .[[1, 2]] + 5

  suppressWarnings({
    .plot <- .data %>%
      ggplot(aes(Domingo, `Cuestionarios acumulados en proceso de firma y sello (1)`)) +
      annotate("segment", x = DIIE_dates[[2, 5]], xend = DIIE_dates[[2, 5]], y = 0, yend = ymax, colour = "orange", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[3, 5]], xend = DIIE_dates[[3, 5]], y = 0, yend = ymax, colour = "orange", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[4, 5]], xend = DIIE_dates[[4, 5]], y = 0, yend = ymax, colour = "orange", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[5, 5]], xend = DIIE_dates[[5, 5]], y = 0, yend = ymax, colour = "orange", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[2, 7]], xend = DIIE_dates[[2, 7]], y = 0, yend = ymax, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[3, 7]], xend = DIIE_dates[[3, 7]], y = 0, yend = ymax, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[4, 7]], xend = DIIE_dates[[4, 7]], y = 0, yend = ymax, colour = "red", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[5, 7]], xend = DIIE_dates[[5, 7]], y = 0, yend = ymax, colour = "red", alpha = 1/2) +
      annotate("text", x = DIIE_dates[[2, 5]], y = ymax + 2, label = str_c("Cierre cap. \n", DIIE_dates[[2, 1]]), size = 2, color = "orange") +
      annotate("text", x = DIIE_dates[[3, 5]], y = ymax + 2, label = str_c("Cierre cap. \n", DIIE_dates[[3, 1]]), size = 2, color = "orange") +
      annotate("text", x = DIIE_dates[[4, 5]], y = ymax + 2, label = str_c("Cierre cap. \n", DIIE_dates[[4, 1]]), size = 2, color = "orange") +
      annotate("text", x = DIIE_dates[[5, 5]], y = ymax + 2, label = str_c("Cierre cap. \n", DIIE_dates[[5, 1]]), size = 2, color = "orange") +
      annotate("text", x = DIIE_dates[[2, 7]], y = ymax + 2, label = str_c("Difusión \n", DIIE_dates[[2, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates[[3, 7]], y = ymax + 2, label = str_c("Difusión \n", DIIE_dates[[3, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates[[4, 7]], y = ymax + 2, label = str_c("Difusión \n", DIIE_dates[[4, 1]]), size = 2, color = "red") +
      annotate("text", x = DIIE_dates[[5, 7]], y = ymax + 2, label = str_c("Difusión \n", DIIE_dates[[5, 1]]), size = 2, color = "red") +
      geom_line(color = "blue" , alpha = 1/8) +
      geom_point(aes(color = -`Cuestionarios acumulados en proceso de firma y sello (1)`,
                     label1 = Domingo, label2 = `Cuestionarios acumulados en proceso de firma y sello (1)`),
                 show.legend = FALSE) +
      scale_x_date(date_breaks = "week", date_labels = "%d %b") +
      ggtitle(.title) +
      theme_classic() +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 9),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10)
      )
  })

  return(ggplotly(.plot, tooltip = c("label1", "label2")))
}

# Local analysis.
# plot_questionnaires_firma_sello_week(database_questionnaires_firma_sello, "2023")
# colocar el acumulado total arriba del gráfico

# Plot on questionnaires set free per week separated by project.
plot_questionnaires_firma_sello_week_project <- function(data, project, .title = "") {

  .data <- data %>%
    filter(Censo == project) %>%
    count(ceiling_date(Registro, "week", week_start = 1)) %>%
    rename(Domingo = names(.)[1], `Cuestionarios acumulados en proceso de firma y sello (1)` = names(.)[2]) %>%
    transmute(Domingo = Domingo - 1, `Cuestionarios acumulados en proceso de firma y sello (1)`)

  if (nrow(.data) == 0) {
    return(NULL)
  }

  ymax <- .data %>%
    arrange(desc(`Cuestionarios acumulados en proceso de firma y sello (1)`)) %>%
    .[[1, 2]] + 5

  .plot <- function(.census) {
    plot <- ggplot(.data, aes(Domingo, `Cuestionarios acumulados en proceso de firma y sello (1)`)) +
      annotate("segment", x = DIIE_dates[[which(DIIE_dates[1] == .census), 5]], xend = DIIE_dates[[which(DIIE_dates[1] == .census), 5]],
               y = 0, yend = ymax, colour = "orange", alpha = 1/2) +
      annotate("segment", x = DIIE_dates[[which(DIIE_dates[1] == .census), 7]], xend = DIIE_dates[[which(DIIE_dates[1] == .census), 7]],
               y = 0, yend = ymax, colour = "red", alpha = 1/2) +
      annotate("text",    x = DIIE_dates[[which(DIIE_dates[1] == .census), 5]], y = ymax + 2,
               label = str_c("Cierre cap. \n", .census), size = 2, color = "orange") +
      annotate("text",    x = DIIE_dates[[which(DIIE_dates[1] == .census), 7]], y = ymax + 2,
               label = str_c("Difusión \n", .census), size = 2, color = "red")

    return(plot)
  }

  suppressWarnings({
    .plot <- .plot(project) +
      geom_line(color = "blue" , alpha = 1/8) +
      geom_point(aes(color = -`Cuestionarios acumulados en proceso de firma y sello (1)`,
                     label1 = Domingo, label2 = `Cuestionarios acumulados en proceso de firma y sello (1)`),
                 show.legend = FALSE) +
      scale_x_date(date_breaks = "month", date_labels = "%d %b") +
      ggtitle(.title) +
      theme_classic() +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 9),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10)
      )
  })

  return(ggplotly(.plot, tooltip = c("label1", "label2")))
}

# Local analysis.
# plot_questionnaires_firma_sello_week_project(database_questionnaires_firma_sello, levels(DIIE_dates[[1]])[1])

# DT questionnaires set free by census.
DT_questionnaires_firma_sello_census <- function(.data, .census) {

  .data %>%
    filter(Censo == .census) %>%
    separate(Folio, into = c("entidad", "Cuestionario"), sep = 2) %>%
    select(1, 2) %>%
    group_by(Cuestionario) %>%
    summarise(Entidades = str_c(entidad, collapse = ", "))
}

# Local analysis.
# DT_questionnaires_firma_sello_census(database_questionnaires_firma_sello, "CNSIPEE")

# Plot on questionnaires set free separated by project.
plot_questionnaires_firma_sello_light <- function(data, .title = "") {

  .data <- data %>%
    count(Registro, Censo) %>%
    rename(`Cuestionarios en proceso de firma y sello (1)` = names(.)[[3]])

  max_day <- .data %>%
    group_by(Censo) %>%
    summarise(y_max = max(`Cuestionarios en proceso de firma y sello (1)`))

  .data <- .data %>%
    left_join(DIIE_dates, by = c("Censo" = "name")) %>%
    left_join(max_day, by = "Censo")

  suppressWarnings({
    .plot <- .data %>%
      ggplot(aes(Registro, `Cuestionarios en proceso de firma y sello (1)`)) +
      geom_rect(aes(xmin = `start CE`, xmax = `end CE`,
                    ymin = 0, ymax = y_max + 1, Responsable = "CE"),
                fill = "green", alpha = 0.1) +
      geom_rect(aes(xmin = prosecution, xmax = diffusion,
                    ymin = 0, ymax = y_max + 1, Responsable = "SPICNG y SAICNG"),
                fill = "red", alpha = 0.3) +
      geom_rect(aes(xmin = `start DIIE`, xmax = `end DIIE`,
                    ymin = 0, ymax = y_max + 1, Responsable = "SOCNG"),
                fill = "orange", alpha = 0.5) +
      geom_point(size = 0.2, color = "blue") +
      facet_grid(Censo ~ ., scales = "free_y") +
      scale_x_date(date_breaks = "week", date_labels = "%d %b") +
      ggtitle(.title) +
      theme(
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1, size = 7),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 7),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10)
      )
  })

  return(ggplotly(.plot))
}

# Local analysis
# plot_questionnaires_firma_sello_light(database_questionnaires_firma_sello)

# Plot on set free questionnaires for entities separte by census
plot_questionnaires_firma_sello_light_entities <- function(data, entity) {

  .data <- data %>%
    filter(Entidad == entity) %>%
    count(Registro, Censo) %>%
    rename(`Cuestionarios en proceso de firma y sello (1)` = names(.)[[3]])

  if (nrow(.data) == 0) {
    return(NULL)
  }

  max_day <- .data %>%
    group_by(Censo) %>%
    summarise(y_max = max(`Cuestionarios en proceso de firma y sello (1)`))

  .data <- .data %>%
    left_join(DIIE_dates, by = c("Censo" = "name")) %>%
    left_join(max_day, by = "Censo")

  suppressWarnings({
    .plot <- .data %>%
      ggplot(aes(Registro, `Cuestionarios en proceso de firma y sello (1)`)) +
      geom_rect(aes(xmin = `start CE`, xmax = `end CE`,
                    ymin = 0, ymax = y_max + 1, Responsable = "CE"),
                fill = "green", alpha = 0.1) +
      geom_rect(aes(xmin = prosecution, xmax = diffusion,
                    ymin = 0, ymax = y_max + 1, Responsable = "SPICNG y SAICNG"),
                fill = "red", alpha = 0.3) +
      geom_rect(aes(xmin = `start DIIE`, xmax = `end DIIE`,
                    ymin = 0, ymax = y_max + 1, Responsable = "SOCNG"),
                fill = "orange", alpha = 0.5) +
      geom_point(size = 1, color = "blue", alpha = 3/4) +
      facet_grid(Censo ~ ., scales = "free_y") +
      scale_x_date(date_breaks = "week", date_labels = "%d %b") +
      theme(
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1, size = 7),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 7),
        axis.title.y = element_blank()
      )
  })

  return(ggplotly(.plot))
}

# Local analysis
# plot_questionnaires_firma_sello_light_entities(database_questionnaires_firma_sello , levels(entities[[1]])[3])

# Count questionnnaires by time range.
count_questionnaires_firma_sello <- function(data, .census, .min = pull(DIIE_dates, 2)[3], .max) {

  if (.census == "GLOBAL") {
    return(nrow(data %>% filter(.min <= Registro & Registro <= .max)))
  }

  return(data %>% filter(Censo == .census) %>% nrow())
}


# EDA about questionnaires "Aclaración de información OC" -----------------

source("functions/db_q_aclaracion_oc.R")

